CREATE TABLE "Materials" (
  "MaterialID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassID" int,
  "Title" varchar(200),
  "FilePath" varchar(255),
  "UploadedAt" timestamp
);

CREATE TABLE "Quizzes" (
  "QuizID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassID" int,
  "Title" varchar(200),
  "CreatedAt" timestamp
);

CREATE TABLE "ClassSchedules" (
  "ScheduleID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassID" int,
  "Day" classschedules_day_enum,
  "StartTime" time,
  "EndTime" time
);

CREATE TABLE "Notifications" (
  "NotificationID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int,
  "Content" text,
  "IsRead" boolean,
  "CreatedAt" timestamp
);

CREATE TABLE "StudentsClasses" (
  "StudentClassID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StudentID" int,
  "ClassID" int,
  "EnrolledAt" timestamp
);

CREATE TABLE "Announcements" (
  "AnnouncementID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassID" int,
  "Title" varchar(200),
  "Content" text,
  "CreatedAt" timestamp
);

CREATE TABLE "Grades" (
  "GradeID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StudentID" int,
  "ClassID" int,
  "TotalGrade" decimal(5,2),
  "UpdatedAt" timestamp
);

CREATE TABLE "Users" (
  "UserID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" varchar(50),
  "LastName" varchar(50),
  "Email" varchar(100) UNIQUE,
  "PasswordHash" varchar(255),
  "Role" users_role_enum,
  "CreatedAt" timestamp
);

CREATE TABLE "Submissions" (
  "SubmissionID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AssignmentID" int,
  "StudentID" int,
  "SubmissionFile" varchar(255),
  "SubmittedAt" timestamp,
  "Grade" decimal(5,2),
  "Feedback" text
);

CREATE TABLE "ClassDiscussions" (
  "DiscussionID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassID" int,
  "UserID" int,
  "Content" text,
  "CreatedAt" timestamp
);

CREATE TABLE "Events" (
  "EventID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassID" int,
  "Title" varchar(200),
  "Description" text,
  "EventDate" datetime,
  "CreatedAt" timestamp
);

CREATE TABLE "ArchivedClasses" (
  "ArchiveID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassID" int,
  "ArchivedAt" timestamp
);

CREATE TABLE "Classes" (
  "ClassID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassName" varchar(100),
  "Section" varchar(50),
  "Subject" varchar(100),
  "TeacherID" int,
  "CreatedAt" timestamp
);

CREATE TABLE "Roles" (
  "RoleID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleName" varchar(50),
  "Permissions" text
);

CREATE TABLE "QuizSubmissions" (
  "SubmissionID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QuizID" int,
  "StudentID" int,
  "Score" decimal(5,2),
  "SubmittedAt" timestamp
);

CREATE TABLE "AdminActions" (
  "ActionID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AdminID" int,
  "ActionDescription" text,
  "PerformedAt" timestamp
);

CREATE TABLE "PeerReviews" (
  "ReviewID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SubmissionID" int,
  "ReviewerID" int,
  "ReviewText" text,
  "Score" decimal(5,2),
  "ReviewedAt" timestamp
);

CREATE TABLE "QuizQuestions" (
  "QuestionID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QuizID" int,
  "QuestionText" text,
  "OptionA" varchar(200),
  "OptionB" varchar(200),
  "OptionC" varchar(200),
  "OptionD" varchar(200),
  "CorrectOption" quizquestions_correctoption_enum
);

CREATE TABLE "Feedback" (
  "FeedbackID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int,
  "ClassID" int,
  "FeedbackText" text,
  "SubmittedAt" timestamp
);

CREATE TABLE "Attendance" (
  "AttendanceID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StudentID" int,
  "ClassID" int,
  "Date" date,
  "Status" attendance_status_enum
);

CREATE TABLE "Assignments" (
  "AssignmentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassID" int,
  "Title" varchar(200),
  "Description" text,
  "DueDate" datetime,
  "CreatedAt" timestamp
);

CREATE TABLE "ParentContacts" (
  "ParentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StudentID" int,
  "ParentName" varchar(100),
  "ContactInfo" varchar(255)
);

CREATE TABLE "DiscussionReplies" (
  "ReplyID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DiscussionID" int,
  "UserID" int,
  "Content" text,
  "CreatedAt" timestamp
);

CREATE TABLE "UserRoles" (
  "UserRoleID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int,
  "RoleID" int,
  "AssignedAt" timestamp
);

ALTER TABLE "Assignments" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "ClassDiscussions" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "ClassDiscussions" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");

ALTER TABLE "Submissions" ADD FOREIGN KEY ("StudentID") REFERENCES "Users" ("UserID");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");

ALTER TABLE "Submissions" ADD FOREIGN KEY ("AssignmentID") REFERENCES "Assignments" ("AssignmentID");

ALTER TABLE "Classes" ADD FOREIGN KEY ("TeacherID") REFERENCES "Users" ("UserID");

ALTER TABLE "DiscussionReplies" ADD FOREIGN KEY ("DiscussionID") REFERENCES "ClassDiscussions" ("DiscussionID");

ALTER TABLE "ArchivedClasses" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "Feedback" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");

ALTER TABLE "QuizQuestions" ADD FOREIGN KEY ("QuizID") REFERENCES "Quizzes" ("QuizID");

ALTER TABLE "AdminActions" ADD FOREIGN KEY ("AdminID") REFERENCES "Users" ("UserID");

ALTER TABLE "Attendance" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "PeerReviews" ADD FOREIGN KEY ("SubmissionID") REFERENCES "Submissions" ("SubmissionID");

ALTER TABLE "Quizzes" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "ClassSchedules" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "Materials" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "ParentContacts" ADD FOREIGN KEY ("StudentID") REFERENCES "Users" ("UserID");

ALTER TABLE "UserRoles" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");

ALTER TABLE "Grades" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "Announcements" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "QuizSubmissions" ADD FOREIGN KEY ("QuizID") REFERENCES "Quizzes" ("QuizID");

ALTER TABLE "DiscussionReplies" ADD FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");

ALTER TABLE "QuizSubmissions" ADD FOREIGN KEY ("StudentID") REFERENCES "Users" ("UserID");

ALTER TABLE "StudentsClasses" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "Attendance" ADD FOREIGN KEY ("StudentID") REFERENCES "Users" ("UserID");

ALTER TABLE "PeerReviews" ADD FOREIGN KEY ("ReviewerID") REFERENCES "Users" ("UserID");

ALTER TABLE "Feedback" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");

ALTER TABLE "UserRoles" ADD FOREIGN KEY ("RoleID") REFERENCES "Roles" ("RoleID");

ALTER TABLE "StudentsClasses" ADD FOREIGN KEY ("StudentID") REFERENCES "Users" ("UserID");

ALTER TABLE "Grades" ADD FOREIGN KEY ("StudentID") REFERENCES "Users" ("UserID");

ALTER TABLE "Events" ADD FOREIGN KEY ("ClassID") REFERENCES "Classes" ("ClassID");
